dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
cache:
  npm: true
services:
  - mongodb
before_script:
  - cp config/default.js config/test.js
env:
  - NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_TOKEN
  app: node-api-skeleton
