version: '3'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - '6379:6379'

  api:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    depends_on:
     - redis
    links:
      - redis
    ports:
      - 3000:3000

networks:
  redis-net:

volumes:
  redis-data:
