version: '3'
services:
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    restart: always
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command: ['redis-server', '--appendonly', 'yes']
    restart: always
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  api:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports:
      - 3000:3000

networks:
  redis-net:

volumes:
  redis-data:
